Add missing include for struct sockaddr on FreeBSD
cc -Wall -Wno-switch -ggdb -fPIC   -DMINOR=\"1\" -DDISABLE_DVBCSA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI -DNO_BACKTRACE -c minisatip.c -o ../build/minisatip.o
In file included from minisatip.c:21:
In file included from ./minisatip.h:6:
./socketworks.h:17:21: error: field has incomplete type 'struct sockaddr'
    struct sockaddr sa;