Add FreeBSD support (#970)
* Add missing include for struct sockaddr on FreeBSD

cc -Wall -Wno-switch -ggdb -fPIC   -DMINOR=\"1\" -DDISABLE_DVBCSA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI -DNO_BACKTRACE -c minisatip.c -o ../build/minisatip.o
In file included from minisatip.c:21:
In file included from ./minisatip.h:6:
./socketworks.h:17:21: error: field has incomplete type 'struct sockaddr'
    struct sockaddr sa;

* Support platforms that don't have SO_BINDTODEVICE

cc -Wall -Wno-switch -ggdb -fPIC -I/usr/local/include  -DMINOR=\"\" -DDISABLE_DVBCSA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI -DNO_BACKTRACE -c minisatip.c -o ../build/minisatip.o
minisatip.c:1857:46: error: use of undeclared identifier 'SO_BINDTODEVICE'
            if (setsockopt(ssdp, SOL_SOCKET, SO_BINDTODEVICE, (void *)&ifr,
                                             ^
minisatip.c:1860:47: error: use of undeclared identifier 'SO_BINDTODEVICE'
            if (setsockopt(ssdp1, SOL_SOCKET, SO_BINDTODEVICE, (void *)&ifr,

* Use correct get_mac_address() implementation on FreeBSD

Properly treat Linux implementation for get_mac_address() as such. The
MacOSX implementation works fine for FreeBSD as well.

cc -Wall -Wno-switch -ggdb -fPIC -I/usr/local/include  -DMINOR=\"\" -DDISABLE_DVBCSA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI -DNO_BACKTRACE -c socketworks.c -o ../build/socketworks.o
socketworks.c:1002:33: error: use of undeclared identifier 'SIOCGIFHWADDR'
                if (ioctl(sock, SIOCGIFHWADDR, &ifr) == 0)
                                ^
socketworks.c:1009:19: error: no member named 'ifr_hwaddr' in 'struct ifreq'
    memcpy(m, ifr.ifr_hwaddr.sa_data, 6);
              ~~~ ^

* Support platforms that don't have SO_PRIORITY

cc -Wall -Wno-switch -ggdb -fPIC -I/usr/local/include  -DMINOR=\"\" -DDISABLE_DVBCSA -DDISABLE_NETCVCLIENT -DDISABLE_DDCI -DDISABLE_T2MI -DNO_BACKTRACE -c socketworks.c -o ../build/socketworks.o
socketworks.c:1567:36: error: use of undeclared identifier 'SO_PRIORITY'
    if (setsockopt(id, SOL_SOCKET, SO_PRIORITY, &d, sizeof(d)))